# Generated by Django 3.1.3 on 2020-11-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productorderposition',
            table='api_product_order_position',
        ),
    ]
