# Generated by Django 3.1.2 on 2020-10-26 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('text', models.TextField(unique=True, verbose_name='Текст')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Гпуппы',
            },
        ),
        migrations.CreateModel(
            name='GroupArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups_in_article', to='articles.article')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups', to='articles.group')),
            ],
            options={
                'db_table': 'articles_group_article',
                'ordering': ['-is_main', 'groups__title'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='groups',
            field=models.ManyToManyField(through='articles.GroupArticle', to='articles.Group'),
        ),
    ]
